VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iSpace"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit



Public Function addBoundaryFunction(ByVal boundaryFunction As String)
End Function

Public Function isIn(x As iPoint) As Boolean
End Function

Public Function distance(x As iPoint, y As iPoint) As Double
End Function

Public Function union(sp As iSpace) As iSpace
End Function

Public Function generateRandomPoint() As iPoint
End Function


